/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <bam.h>



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_bam_1open(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  bamFile result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = bam_open((char const *)arg1,(char const *)arg2);
  {
    bamFile * resultptr = (bamFile *) malloc(sizeof(bamFile));
    memmove(resultptr, &result, sizeof(bamFile));
    *(bamFile **)&jresult = resultptr;
  }
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_bam_1close(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  bamFile arg1 ;
  bamFile *argp1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(bamFile **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null bamFile");
    return 0;
  }
  arg1 = *argp1; 
  result = (int)bam_close(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_bam_1hdr_1read(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  bamFile arg1 ;
  bamFile *argp1 ;
  bam_hdr_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(bamFile **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null bamFile");
    return 0;
  }
  arg1 = *argp1; 
  result = (bam_hdr_t *)bam_hdr_read(arg1);
  *(bam_hdr_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_bam_1read1(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  bamFile arg1 ;
  bam1_t *arg2 = (bam1_t *) 0 ;
  bamFile *argp1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(bamFile **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null bamFile");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = *(bam1_t **)&jarg2; 
  result = (int)bam_read1(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_bam_1init1(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  bam1_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (bam1_t *)bam_init1();
  *(bam1_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_bam_1destroy1(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bam1_t *arg1 = (bam1_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(bam1_t **)&jarg1; 
  bam_destroy1(arg1);
}


SWIGEXPORT jstring JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_bam_1get_1qname(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  bam1_t *arg1 = (bam1_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(bam1_t **)&jarg1; 
  result = (char *)bam_get_qname(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}



SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1flags(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bam1_t *b = (bam1_t *) jarg1 ;
  return (jint)b->core.flag;
}


SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1alignment_1start(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bam1_t *b = (bam1_t *) jarg1 ;
  if( (b->core.flag&BAM_FUNMAP) ) return 0;
  
  return (jint)(b->core.pos+1);
}

SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1read_1length(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bam1_t *b = (bam1_t *) jarg1 ;
  return (jint) b->core.l_qseq;
}

SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1read_1base_1at(JNIEnv *jenv, jclass jcls, jlong jarg1,jint index) {
  bam1_t *b = (bam1_t *) jarg1 ;
  return (jint)"=ACMGRSVTWYHKDBN"[bam1_seqi(bam1_seq(b),index)];
}


SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1read_1qual_1at(JNIEnv *jenv, jclass jcls, jlong jarg1,jint index) {
  bam1_t *b = (bam1_t *) jarg1 ;
  uint8_t *s = bam_get_qual(b);
  if (s[0] == 0xff) return (jint)-1;
 return (jint)s[index];
 }

SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1reference_1index(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bam1_t *b = (bam1_t *) jarg1 ;
 return (jint)b->core.tid;
 }

SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1mapping_1quality(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bam1_t *b = (bam1_t *) jarg1 ;
 return (jint)b->core.qual;
 }


SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1mate_1reference_1index(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bam1_t *b = (bam1_t *) jarg1 ;
 return (jint)b->core.mtid;
 }

SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1mate_1alignment_1start(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bam1_t *b = (bam1_t *) jarg1 ;
 return (jint)b->core.mpos + 1;
 }


SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1cigar_1num_1elements  (JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bam1_t *b = (bam1_t *) jarg1 ;
 return (jint)b->core.n_cigar;
  }

SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1cigar_1op (JNIEnv *jenv, jclass jcls, jlong jarg1, jint index) {
  bam1_t *b = (bam1_t *) jarg1 ;
  uint32_t *cigar = (uint32_t *)bam_get_cigar(b);
  if(b->core.n_cigar==0) return 0;
  return (jint)bam_cigar_opchr(cigar[index]);
  }



SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1cigar_1length(JNIEnv *jenv, jclass jcls, jlong jarg1, jint index) {
  bam1_t *b = (bam1_t *) jarg1 ;
  uint32_t *cigar = (uint32_t *)bam_get_cigar(b);
  if((jint)b->core.n_cigar==0) return 0;
  return (jint)bam_cigar_oplen(cigar[index]);
  }


SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1inferred_1size  (JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bam1_t *b = (bam1_t *) jarg1 ;
 return (jint)b->core.isize;
  }
  
SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_bam_1hdr_1count_1references  (JNIEnv *jenv, jclass jcls, jlong jarg1) {
 bam_hdr_t *h = (bam_hdr_t *) jarg1 ;
 return (jint)h->n_targets;
  }

SWIGEXPORT jstring JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_bam_1hdr_1get_1reference_1name(JNIEnv *jenv, jclass jcls, jlong jarg1, jint index) {
  bam_hdr_t *h = (bam_hdr_t *) jarg1 ;
  return (*jenv)->NewStringUTF(jenv, (const char *)h->target_name[index]);
  }



SWIGEXPORT jint JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_bam_1hdr_1get_1reference_1length(JNIEnv *jenv, jclass jcls, jlong jarg1, jint index) {
  bam_hdr_t *h = (bam_hdr_t *) jarg1 ;
  return (jint)h->target_len[index];
  }

SWIGEXPORT jbyteArray JNICALL Java_htsjdk_samtools_jni_HtsJniBindingsJNI_my_1bam_1get_1aux (JNIEnv *jenv, jclass jcls, jlong jarg1) {
 bam1_t *b = (bam1_t *) jarg1 ;
 uint8_t *s1 = bam_get_aux(b); // aux
 uint8_t *s2 = b->data + b->l_data;
 size_t len = s2 - s1;
 jbyteArray result = (*jenv)->NewByteArray(jenv, len);
 (*jenv)->SetByteArrayRegion(jenv, result, 0, len, (const jbyte*)s1 );
 return result;
 }
  
#ifdef __cplusplus
}
#endif

