/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package htsjdk.samtools.jni;

public class HtsJniBindingsJNI {
  public final static native long bam_open(String jarg1, String jarg2);
  public final static native int bam_close(long jarg1);
  public final static native long bam_hdr_read(long jarg1);
  public final static native int bam_read1(long jarg1, long jarg2);
  public final static native long bam_init1();
  public final static native void bam_destroy1(long jarg1);
  public final static native String bam_get_qname(long jarg1);
  
  public final static native int my_bam_get_flags(long jarg1);
  public final static native int my_bam_get_alignment_start(long jarg1);
  public final static native int my_bam_get_read_length(long jarg1);
  public final static native int my_bam_get_read_base_at(long jarg1,int index);
  public final static native int my_bam_get_read_qual_at(long jarg1,int index);
  public final static native int my_bam_get_reference_index(long jarg1);
  public final static native int my_bam_get_mapping_quality(long jarg1);
  
  public final static native int my_bam_get_mate_reference_index(long jarg1);
  public final static native int my_bam_get_mate_alignment_start(long jarg1);
  
  public final static native int my_bam_get_cigar_num_elements(long jarg1);
  public final static native int my_bam_get_cigar_op(long jarg1,int index);
  public final static native int my_bam_get_cigar_length(long jarg1,int index);
  
  public final static native int my_bam_get_inferred_size(long jarg1);

  public final static native int bam_hdr_count_references(long jarg1);
  public final static native String bam_hdr_get_reference_name(long jarg1,int index);
  public final static native int bam_hdr_get_reference_length(long jarg1,int index);
  
  public final static native byte[] my_bam_get_aux(long jarg1);

}
